spring:
  application:
    name: vacancy-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/vacancy_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
